import React, { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { api } from '../api.js';
import { Modal, fmtUGX, useToast, Empty } from '../components/ui.jsx';
import NavIcon from '../components/NavIcon.jsx';
const localDate = () => new Date().toLocaleDateString('en-CA', {timeZone:'Africa/Kampala'});
const categories = {bachelor:'University student', ldc:'LDC tenant', other:'Other tenant'};
function termEnd(start, months=3) {
  const [y,m,d]=start.split('-').map(Number);
  const last=new Date(Date.UTC(y,m-1+months+1,0)).getUTCDate();
  const target=new Date(Date.UTC(y,m-1+months,Math.min(d,last)));
  return new Date(target.getTime()-86400000).toISOString().slice(0,10);
}
export default function Occupancy() {
  const [params,setParams]=useSearchParams();
  const roomFilter=Number(params.get('room'))||null;
  function closeAdd(){setAdding(false);const next=new URLSearchParams(params);next.delete('add');setParams(next,{replace:true});}
  const [month,setMonth]=useState(localDate().slice(0,7));
  const [example,setExample]=useState(false);
  const [data,setData]=useState(null);
  const [residents,setResidents]=useState([]);
  const [rooms,setRooms]=useState([]);
  const [defaults,setDefaults]=useState(null);
  const [adding,setAdding]=useState(params.get('add')==='1');
  const [editing,setEditing]=useState(null);
  const [collecting,setCollecting]=useState(null);
  const [detail,setDetail]=useState(null);
  const [query,setQuery]=useState('');
  const [error,setError]=useState('');
  const toast=useToast();
  function load() {
    setError('');
    return api.get(example?'/occupancy/example':`/occupancy?month=${month}`).then(setData).catch(e=>{setData(null);setError(e.message);});
  }
  useEffect(()=>{let cancelled=false;setData(null);setError('');api.get(example?'/occupancy/example':`/occupancy?month=${month}`).then(d=>{if(!cancelled)setData(d);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[month,example]);
  useEffect(()=>{Promise.all([api.get('/residents'),api.get('/rooms'),api.get('/settings')]).then(([r,rm,settings])=>{setResidents(r);setRooms(rm);setDefaults(settings);}).catch(e=>{toast(e.message,'error');setDefaults({});});},[!!adding,!!editing]);
  const summary=data?.summary;
  const shown=(data?.stays||[]).filter(s=>(!roomFilter||example||s.room_id===roomFilter)&&`${s.first_name} ${s.last_name} ${s.room_name} ${categories[s.tenant_type]}`.toLowerCase().includes(query.toLowerCase()));
  function add() { setExample(false);setAdding(true); }
  return <div className="stagger">
    <div className="page-head"><div><div className="eyebrow">Stays & rent · Occupancy → Income</div><h1 className="page-title">Dashboard</h1><p className="page-sub">Who is staying, when space opens up, and what each month is worth.</p></div><div className="occupancy-actions"><button className="btn" onClick={()=>setExample(!example)}>{example?'Back to live records':'View example'}</button><button className="btn btn-primary" onClick={add}>+ Add stay</button></div></div>
    <div className="occupancy-controls"><div className="field"><label htmlFor="occupancy-month">Reporting month</label><input id="occupancy-month" className="input" type="month" min="2000-01" max="2100-12" value={example?data?.month||month:month} disabled={example} onChange={e=>{if(e.target.value)setMonth(e.target.value);}} /></div><p className="dim">{data?`Occupancy and balances as of ${data.as_of}.`:'Loading month…'} Monthly tenants pay full calendar months, including partial stays.</p></div>
    {roomFilter&&!example&&<div className="occupancy-notice">Viewing {rooms.find(r=>r.id===roomFilter)?.name||'selected room'} · Summary figures above cover the whole hostel. <Link to={`/rooms/${roomFilter}`}>Back to room</Link> · <Link to="/">Show all rooms</Link></div>}
    {example&&<div className="occupancy-notice">Example only: two university students at UGX 1.6m each for three months, an LDC tenant at UGX 850,000 per month, and another tenant at UGX 600,000 per month. These are illustrative rates, not saved agreements.</div>}
    {error&&<div className="toast error" role="alert">{error} <button className="btn btn-sm" onClick={load}>Retry</button></div>}
    <div className="stat-grid occupancy-stats">
      <Metric title="Occupied beds" value={summary?`${summary.occupied} / ${summary.beds}`:'—'} note={summary?`${summary.rooms_occupied} of ${summary.rooms_total} rooms in use`:'Across all rooms'} />
      <Metric title="Rent allocated to this month" value={summary?fmtUGX(summary.expected_rent):'—'} note="From priced stay agreements" />
      <Metric title="Cash received this month" value={summary?fmtUGX(summary.cash_this_month):'—'} note="Actual recorded rent receipts" />
      <Metric title="Unpaid rent due" value={summary?fmtUGX(summary.due_balance):'—'} note="Due invoices less recorded receipts" />
    </div>
    {data?.unpriced.length>0&&<div className="occupancy-notice"><strong>{data.unpriced.length} occupants have no rent agreement.</strong> Their beds count as occupied, but income stays unpriced. Add an agreement to include their rent.<div className="unpriced-list">{data.unpriced.filter(r=>!roomFilter||example||r.room_id===roomFilter).map(r=><button className="btn btn-sm" key={r.id} onClick={()=>setAdding(r)}>{r.first_name} {r.last_name} +</button>)}</div></div>}
    <div className="occupancy-explainer"><NavIcon name="payments" /><p><strong>A semester payment is not one month's rent.</strong> UGX 1,600,000 for three full months is approximately UGX 533,333 per month per resident. A fully occupied double room brings approximately UGX 1,066,667 per month. Receipts track when the money actually arrives.</p></div>
    <div className="section-title">Room availability & monthly value</div>
    <div className="occupancy-room-grid">{data?.rooms.filter(r=>!roomFilter||example||r.id===roomFilter).map(r=><RoomLink room={r} example={example} key={r.id}><div className="occupancy-room-top"><strong>{r.name}{!example&&' ↗'}</strong><span>{r.occupied}/{r.capacity} beds</span></div><div className="occupancy-meter"><span style={{width:`${Math.min(100,r.occupancy_percent)}%`}} /></div><p className="dim">{r.occupancy_percent}% of bed-days booked this month{r.status==='maintenance'?' · Maintenance':''}</p><div className="occupancy-room-money">{fmtUGX(r.monthly_rent)}<span> allocated rent</span></div>{r.tenants.map((t,i)=><div className="occupancy-tenant" key={i}><span>{t.name}</span><small>{t.unpriced?'Agreement needed':`Until ${t.end_date}`}</small></div>)}{!r.tenants.length&&<div className="occupancy-tenant dim">No tenants on {data.as_of}</div>}</RoomLink>)}</div>
    <div className="page-head" style={{marginTop:28,marginBottom:14}}><div className="section-title" style={{margin:0}}>Stay agreements</div><input className="input occupancy-search" aria-label="Search stay agreements" placeholder="Search tenant, room or category…" value={query} onChange={e=>setQuery(e.target.value)} /></div>
    {data&&!shown.length?<div className="card"><Empty text="No agreements yet. Add each tenant's dates and price to start tracking income." /></div>:<div className="card" style={{padding:0}}><div className="table-wrap"><table className="table"><thead><tr><th>Tenant / room</th><th>Stay period</th><th>Agreed rate</th><th>This month's rent</th><th>Due balance</th><th>Actions</th></tr></thead><tbody>{shown.map(s=><tr key={s.id}><td><strong>{s.first_name} {s.last_name}</strong><div className="dim">{s.room_name} · {categories[s.tenant_type]}</div></td><td>{s.start_date}<br/>{s.end_date}<div className={`stay-state ${s.state==='Ended'?'dim':''}`}>{s.state}{s.state==='Staying'&&s.end_date>=data.as_of&&Math.ceil((Date.parse(s.end_date)-Date.parse(data.as_of))/86400000)<=30?' · Ending within 30 days':''}</div></td><td>{fmtUGX(s.amount)}<div className="dim">{s.billing_basis==='fixed'?'Total for the stay':'Per calendar month'}</div></td><td>{fmtUGX(s.monthly_rent)}</td><td><strong style={{color:s.due?'var(--red)':'var(--green)'}}>{fmtUGX(s.due)}</strong></td><td><div className="occupancy-actions"><button className="btn btn-sm" onClick={()=>setDetail(s)}>Ledger</button>{!example&&!s.receipts.length&&<button className="btn btn-sm" onClick={()=>setEditing(s)}>Edit</button>}{!example&&s.balance>0&&month===localDate().slice(0,7)&&<button className="btn btn-sm btn-primary" onClick={()=>setCollecting(s)}>Record receipt</button>}</div></td></tr>)}</tbody></table></div></div>}
    <div className="card occupancy-policy"><strong>How the figures work</strong><p>Monthly rent is charged in full for every calendar month touched by the stay. Fixed-term rent is invoiced once at move-in and allocated across the stay for monthly reporting; partial months affect the allocation, not the agreed bill. End dates include the last occupied night. Advance payments remain visible as cash while rent is spread across the months it covers. Whole-shilling rounding preserves each agreement’s exact total. These figures exclude deposits and legacy/manual payments.</p><p><strong>Coming up:</strong> {summary?.ending_soon??'—'} agreements end in the next 30 days. Renew by adding the next stay with its new dates and rate. Terms can be edited until the first receipt is recorded; paid agreements keep their original ledger.</p></div>
    {adding&&defaults&&<StayForm defaults={defaults} initialRoomId={roomFilter} resident={adding===true?null:adding} residents={residents} rooms={rooms} onClose={closeAdd} onSaved={()=>{closeAdd();load();}} />}
    {editing&&defaults&&<StayForm defaults={defaults} stay={editing} residents={residents} rooms={rooms} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);load();}} />}
    {collecting&&defaults&&<ReceiptForm defaults={defaults} stay={collecting} onClose={()=>setCollecting(null)} onSaved={()=>{setCollecting(null);load();}} />}
    {detail&&<Modal title={`${detail.first_name} ${detail.last_name} · Rent ledger`} onClose={()=>setDetail(null)}><p className="dim" style={{marginBottom:16}}>Total agreed rent: {fmtUGX(detail.total_rent)} · Receipts to {data.as_of}: {fmtUGX(detail.paid)}</p><div className="table-wrap"><table className="table"><thead><tr><th>Coverage</th><th>Due</th><th>Billed</th><th>Paid</th><th>Balance</th></tr></thead><tbody>{detail.invoices.map(i=><tr key={i.id}><td>{i.period_start}<br/>{i.period_end}</td><td>{i.due_date}</td><td>{fmtUGX(i.amount)}</td><td>{fmtUGX(i.paid)}</td><td>{fmtUGX(i.balance)}</td></tr>)}</tbody></table></div><h3 className="section-title" style={{marginTop:20}}>Receipt history</h3>{detail.receipts.length?detail.receipts.map(r=><div className="fact-row" key={r.id}><span>{r.paid_on} · {r.method.replace('_',' ')}<br/>{r.reference||'No reference'}</span><strong>{fmtUGX(r.amount)}</strong></div>):<p className="dim">No receipts recorded.</p>}</Modal>}
  </div>;
}
function Metric({title,value,note}) {return <div className="stat-card"><div className="stat-value" style={{fontSize:24}}>{value}</div><div className="stat-label">{title}</div><p className="metric-note">{note}</p></div>;}
function StayForm({defaults={},initialRoomId,resident,stay,residents,rooms,onClose,onSaved}) {
  const toast=useToast();const [busy,setBusy]=useState(false);
  const [form,setForm]=useState({resident_id:stay?.resident_id||resident?.id||'',room_id:stay?.room_id||initialRoomId||resident?.room_id||'',tenant_type:stay?.tenant_type||defaults.default_tenant_type||'bachelor',billing_basis:stay?.billing_basis||defaults.default_billing_basis||'fixed',amount:stay?.amount||'',start_date:stay?.start_date||localDate(),end_date:stay?.end_date||termEnd(localDate()),notes:stay?.notes||''});
  const set=(k,v)=>setForm(f=>({...f,[k]:v}));
  async function submit(e){e.preventDefault();if(busy)return;setBusy(true);try{await (stay?api.put(`/occupancy/stays/${stay.id}`,{...form,amount:Number(form.amount)}):api.post('/occupancy/stays',{...form,amount:Number(form.amount)}));toast('Stay saved and rent invoices created.');onSaved();}catch(e){toast(e.message,'error');}finally{setBusy(false);}}
  return <Modal title={stay?"Edit stay & rent agreement":"Add stay & rent agreement"} onClose={onClose}><form onSubmit={submit}>
    <div className="form-row"><Field label="Tenant" id="stay-tenant"><select id="stay-tenant" className="select" required value={form.resident_id} onChange={e=>{const r=residents.find(r=>r.id===Number(e.target.value));setForm(f=>({...f,resident_id:e.target.value,room_id:initialRoomId||r?.room_id||''}));}}><option value="">Select a registered resident</option>{residents.map(r=><option value={r.id} key={r.id}>{r.first_name} {r.last_name}</option>)}</select></Field><Field label="Room" id="stay-room"><select id="stay-room" className="select" required value={form.room_id} onChange={e=>set('room_id',e.target.value)}><option value="">Choose room</option>{rooms.map(r=><option value={r.id} key={r.id}>{r.name} · {r.capacity} beds</option>)}</select></Field></div>
    <div className="form-row"><Field label="Tenant category" id="stay-category"><select id="stay-category" className="select" value={form.tenant_type} onChange={e=>set('tenant_type',e.target.value)}>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Rent agreement" id="stay-basis"><select id="stay-basis" className="select" value={form.billing_basis} onChange={e=>set('billing_basis',e.target.value)}><option value="fixed">Fixed term / semester total</option><option value="monthly">Monthly rent</option></select></Field></div>
    <div className="form-row"><Field label="First occupied day" id="stay-start"><input id="stay-start" className="input" type="date" required value={form.start_date} onChange={e=>{const start=e.target.value;setForm(f=>({...f,start_date:start,end_date:start?termEnd(start):''}));}} /></Field><Field label="Last occupied day" id="stay-end"><input id="stay-end" className="input" type="date" required min={form.start_date} value={form.end_date} onChange={e=>set('end_date',e.target.value)} /></Field></div>
    <button className="btn btn-sm" type="button" onClick={()=>set('end_date',termEnd(form.start_date))}>Use 3-month semester</button>
    <Field label={form.billing_basis==='fixed'?'Total rent for this stay (UGX)':'Full monthly rent (UGX)'} id="stay-rate"><input id="stay-rate" className="input" type="number" min="1" max="1000000000" step="1" required value={form.amount} onChange={e=>set('amount',e.target.value)} placeholder={form.billing_basis==='fixed'?'e.g. 1600000':'Enter the agreed monthly rate'} /></Field>
    <p className="form-help">Rates are per resident. LDC and other tenants can use either agreement type. Monthly partial stays are billed as full calendar months. Room capacity and overlapping stays are checked when saving.</p>
    <Field label="Agreement notes" id="stay-notes"><textarea id="stay-notes" className="textarea" value={form.notes} onChange={e=>set('notes',e.target.value)} placeholder="University, programme, agreed terms…" /></Field><button className="btn btn-primary" disabled={busy} style={{width:'100%'}}>{busy?'Saving…':stay?'Save changes & update invoices':'Save stay & create invoices'}</button>
  </form></Modal>;
}
function Field({label,id,children}) {return <div className="field"><label htmlFor={id}>{label}</label>{children}</div>;}
function ReceiptForm({defaults={},stay,onClose,onSaved}) {
  const unpaid=stay.invoices.filter(i=>i.balance>0);const toast=useToast();const [busy,setBusy]=useState(false);
  const [form,setForm]=useState({invoice_id:unpaid[0]?.id||'',amount:'',paid_on:localDate(),method:defaults.default_payment_method||'cash',reference:''});const invoice=unpaid.find(i=>i.id===Number(form.invoice_id));const set=(k,v)=>setForm(f=>({...f,[k]:v}));
  async function submit(e){e.preventDefault();if(busy)return;setBusy(true);try{await api.post('/occupancy/receipts',{...form,amount:Number(form.amount)});toast('Receipt recorded. Balance updated.');onSaved();}catch(e){toast(e.message,'error');}finally{setBusy(false);}}
  return <Modal title={`Record receipt · ${stay.first_name} ${stay.last_name}`} onClose={onClose}><form onSubmit={submit}><Field label="Apply payment to invoice" id="receipt-invoice"><select id="receipt-invoice" className="select" value={form.invoice_id} onChange={e=>set('invoice_id',e.target.value)}>{unpaid.map(i=><option value={i.id} key={i.id}>{i.period_start} – {i.period_end} · {fmtUGX(i.balance)} remaining</option>)}</select></Field><div className="form-row"><Field label="Amount received (UGX)" id="receipt-amount"><input id="receipt-amount" className="input" type="number" min="1" max={invoice?.balance} step="1" required value={form.amount} onChange={e=>set('amount',e.target.value)} /></Field><Field label="Date received" id="receipt-date"><input id="receipt-date" className="input" type="date" required max={localDate()} value={form.paid_on} onChange={e=>set('paid_on',e.target.value)} /></Field></div><Field label="Payment method" id="receipt-method"><select id="receipt-method" className="select" value={form.method} onChange={e=>set('method',e.target.value)}>{['cash','bank','mtn_momo','airtel_money','other'].map(m=><option key={m} value={m}>{m.replace('_',' ')}</option>)}</select></Field><Field label="Receipt / transaction reference" id="receipt-reference"><input id="receipt-reference" className="input" value={form.reference} onChange={e=>set('reference',e.target.value)} /></Field><p className="form-help">Record money actually received. Partial payments reduce the balance; recording this receipt does not initiate a bank or mobile-money transfer.</p><button className="btn btn-primary" disabled={busy}>{busy?'Recording…':'Record receipt'}</button></form></Modal>;
}

function RoomLink({room,example,children}) { return example?<div className="card occupancy-room">{children}</div>:<Link className="card occupancy-room room-card-link" to={`/rooms/${room.id}`}>{children}</Link>; }
