import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api,getToken} from '../api.js';
import {fmtUGX,Empty,useToast} from '../components/ui.jsx';
import Brand from '../components/Brand.jsx';
const labels={bachelor:'University students',ldc:'LDC tenants',other:'Other tenants'};
export default function Reports(){
 const toast=useToast();
 const [month,setMonth]=useState(new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Kampala'}).slice(0,7)),[room,setRoom]=useState(''),[data,setData]=useState(null),[error,setError]=useState(''),[tab,setTab]=useState('balances'),[downloading,setDownloading]=useState(false),[roomOptions,setRoomOptions]=useState([]),[retry,setRetry]=useState(0);
 const query=new URLSearchParams({month,...(room?{room}:{})}).toString();
 useEffect(()=>{let cancelled=false;setData(null);setError('');api.get(`/reports?${query}`).then(d=>{if(!cancelled){setData(d);setRoomOptions(d.room_options);}}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[query,retry]);
 async function exportCsv(){setDownloading(true);try{const res=await fetch(`/api/reports?${query}&export=${tab}`,{headers:{Authorization:`Bearer ${getToken()}`}});if(!res.ok)throw Error((await res.json()).error||'Export failed');const url=URL.createObjectURL(await res.blob());const link=document.createElement('a');link.href=url;link.download=`new-nana-${tab}-${month}.csv`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('CSV downloaded');}catch(e){toast(e.message,'error');}finally{setDownloading(false);}}
 const max=Math.max(1,...(data?.trend||[]).flatMap(t=>[t.rent,t.cash]));
 return <div className="stagger finance-report">
  <div className="page-head"><div><div className="eyebrow">Finance · Management reporting</div><h1 className="page-title">Reports</h1><p className="page-sub">Understand monthly value, collections and the rent still due.</p></div><div className="occupancy-actions report-no-print"><button className="btn" disabled={!data} onClick={()=>window.print()}>Print report</button><button className="btn btn-primary" disabled={!data||downloading} onClick={exportCsv}>{downloading?'Exporting…':'Export current table · CSV'}</button></div></div>
  <div className="report-print-brand"><Brand/><strong>{data?.hostel.hostel_name}</strong></div>
  <div className="report-filters card"><div className="field"><label htmlFor="report-month">Reporting month</label><input id="report-month" className="input" type="month" min="2000-01" max="2100-12" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></div><div className="field"><label htmlFor="report-room">Room</label><select id="report-room" className="select" value={room} onChange={e=>setRoom(e.target.value)}><option value="">All rooms</option>{roomOptions.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div><p className="dim">{data?`Balances as of ${data.as_of} · ${data.summary.occupancy_percent}% of available bed-days booked.`:'Loading report…'}</p></div>
  {error&&<p className="occupancy-notice" role="alert">{error} <button className="btn btn-sm" onClick={()=>setRetry(n=>n+1)}>Retry</button></p>}
  {!data&&!error&&<p role="status">Loading finance report…</p>}
  {data&&<>
   {data.forecast&&<p className="occupancy-notice">Future reporting period: rent and invoices are scheduled values. Cash only includes receipts already recorded.</p>}
   <div className="stat-grid occupancy-stats">{[['Allocated rent',data.summary.allocated_rent,'Value of stays covering this month'],['Invoices due this month',data.summary.invoiced,'Full bills, including semester invoices'],['Cash received',data.summary.cash_received,'Rent receipts dated in this month'],['Unpaid rent due',data.summary.due_balance,'Balances due by the report date']].map(([label,value,note])=><div className="stat-card" key={label}><div className="stat-value">{fmtUGX(value)}</div><div className="stat-label">{label}</div><div className="dim report-stat-note">{note}</div></div>)}</div>
   <p className="form-help">Reports use the stay rent ledger. Deposits, manual/legacy payments and expenses are excluded; these figures do not represent profit. {data.summary.unpriced} occupants in this scope have no priced rent agreement.</p>
   <div className="reports-grid"><section className="card"><h2 className="section-title">Rent value & cash · six months</h2><div className="report-legend"><span className="rent">Allocated rent</span><span className="cash">Cash received</span></div>{data.trend.map(t=><div className="report-trend-row" key={t.month}><strong>{t.month}</strong><div><div className="report-bar-row"><span className="report-bar rent" style={{width:`${100*t.rent/max}%`}}/><span>{fmtUGX(t.rent)}</span></div><div className="report-bar-row"><span className="report-bar cash" style={{width:`${100*t.cash/max}%`}}/><span>{fmtUGX(t.cash)}</span></div></div></div>)}</section><section className="card"><h2 className="section-title">Outstanding rent by age</h2><p className="form-help">Age is measured from the invoice’s due date, after receipts through {data.as_of}.</p>{data.aging.map(a=><div className="report-fact" key={a.label}><span>{a.label}</span><strong>{fmtUGX(a.amount)}</strong></div>)}<h3 className="section-title" style={{marginTop:24}}>Collections by method</h3>{data.methods.length?data.methods.map(m=><div className="report-fact" key={m.method}><span>{m.method.replaceAll('_',' ')} · {m.count} receipts</span><strong>{fmtUGX(m.amount)}</strong></div>):<p className="dim">No rent receipts this month.</p>}</section></div>
   <section className="card"><h2 className="section-title">Tenant categories</h2><ReportTable headings={['Category','Monthly rent value','Cash this month','Unpaid due']} rows={data.groups.map(g=>[labels[g.type],fmtUGX(g.rent),fmtUGX(g.cash),fmtUGX(g.due)])}/></section>
   <section className="card"><div className="report-tabs" role="tablist" aria-label="Report tables">{[['balances','Unpaid balances'],['receipts','Rent receipts'],['rent','Rent allocation'],['rooms','Room occupancy']].map(([key,label])=><button type="button" role="tab" aria-selected={tab===key} key={key} className={`btn btn-sm ${tab===key?'btn-primary':''}`} onClick={()=>setTab(key)}>{label}</button>)}</div>
   {tab==='balances'&&<ReportTable headings={['Resident / room','Due date','Invoice','Paid','Balance','Age']} rows={data.outstanding.map(i=>[<>{i.resident_name}<br/><Link to={`/rooms/${i.room_id}`}>{i.room_name}</Link></>,i.due_date,fmtUGX(i.amount),fmtUGX(i.paid),fmtUGX(i.balance),i.days_overdue?`${i.days_overdue} days`:'Due today'])}/>}
   {tab==='receipts'&&<ReportTable headings={['Resident','Room','Received','Method','Reference','Amount']} rows={data.receipts.map(r=>[r.resident_name,r.room_name,r.paid_on,r.method.replaceAll('_',' '),r.reference||'—',fmtUGX(r.amount)])}/>}
   {tab==='rent'&&<ReportTable headings={['Resident','Room','Category','Stay period','Monthly value']} rows={data.allocations.map(s=>[`${s.first_name} ${s.last_name}`,s.room_name,labels[s.tenant_type],`${s.start_date} → ${s.end_date}`,fmtUGX(s.monthly_rent)])}/>}
   {tab==='rooms'&&<ReportTable headings={['Room','Beds occupied','Booked bed-days','Monthly occupancy','Monthly rent']} rows={data.rooms.map(r=>[<Link to={`/rooms/${r.id}`}>{r.name}</Link>,`${r.occupied} / ${r.capacity}`,r.bed_days,`${r.occupancy_percent}%`,fmtUGX(r.monthly_rent)])}/>}
   </section>
   <footer className="report-footer"><strong>{data.hostel.hostel_name}</strong><p>{[data.hostel.address,data.hostel.phone,data.hostel.email].filter(Boolean).join(' · ')}</p><p>{data.hostel.report_footer}</p><p className="form-help">Rent is allocated over stay dates; invoices use their due dates; cash uses receipt dates. Maintenance rooms are excluded from the available-bed occupancy rate. No maximum-rate income is assumed for empty or unpriced beds.</p></footer>
  </>}
 </div>;
}
function ReportTable({headings,rows}){return rows.length?<div className="table-wrap"><table className="table"><thead><tr>{headings.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>:<Empty text="No records for this report period and room."/>;}
