import React, { useEffect, useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { api } from '../api.js';
import { Avatar, Badge, Empty, Modal, TRADES, fmtDateTime, fmtUGX, useToast } from '../components/ui.jsx';
import { RoomForm } from './Rooms.jsx';
const tenantTypes={bachelor:'University student',ldc:'LDC tenant',other:'Other tenant'};
const tabs=['Overview','Occupant history','Rent & receipts','Repairs','Visits','Inspections'];
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Kampala'});

export default function RoomPage() {
  const {id}=useParams();const [params,setParams]=useSearchParams();
  const active=tabs.includes(params.get('tab'))?params.get('tab'):'Overview';
  const [room,setRoom]=useState(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
  const [editing,setEditing]=useState(false);const [repairing,setRepairing]=useState(false);const [inspecting,setInspecting]=useState(false);
  const [updating,setUpdating]=useState(null);const toast=useToast();
  function load(){setError('');return api.get(`/rooms/${id}/history`).then(setRoom).catch(e=>setError(e.message));}
  useEffect(()=>{let cancelled=false;setLoading(true);setRoom(null);setError('');api.get(`/rooms/${id}/history`).then(r=>{if(!cancelled)setRoom(r);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[id]);
  async function repairStatus(repair,status){setUpdating(repair.id);try{await api.put(`/maintenance/${repair.id}`,{status});await load();toast('Repair status updated.');}catch(e){toast(e.message,'error');}finally{setUpdating(null);}}
  if(loading)return <div className="card" role="status">Loading room history…</div>;
  if(!room)return <div className="card"><h1 className="page-title">Room unavailable</h1><p className="dim" role="alert">{error||'Room not found.'}</p><Link to="/rooms" className="btn" style={{marginTop:16}}>Back to rooms</Link></div>;
  const invoices=room.stays.flatMap(s=>s.invoices.map(i=>({...i,resident_name:`${s.first_name} ${s.last_name}`})));
  const historyCount=room.stays.length+room.legacy_assignments.length;
  const counts={'Occupant history':historyCount,'Repairs':room.repairs.length,'Visits':room.visits.length,'Inspections':room.inspections.length};
  return <div className="stagger">
    <Link className="room-back" to="/rooms">← All rooms</Link>
    <div className="page-head"><div><div className="eyebrow">Room management · {room.floor||'Floor not specified'}</div><h1 className="page-title">{room.name}</h1><p className="page-sub">{room.type.charAt(0).toUpperCase()+room.type.slice(1)} room · {room.capacity} beds · Occupancy and activity in one place</p></div><div className="occupancy-actions"><Badge value={room.status}/><button className="btn" onClick={()=>setEditing(true)}>Edit room</button><Link className="btn btn-primary" to={`/?room=${room.id}&add=1`}>+ Add stay</Link></div></div>
    {error&&<p className="occupancy-notice" role="alert">{error} <button className="btn btn-sm" onClick={load}>Retry</button></p>}
    <div className="stat-grid room-summary-grid"><Stat title="Occupied beds now" value={`${room.occupants.length} / ${room.capacity}`} note={`${Math.max(0,room.capacity-room.occupants.length)} vacant beds`} /><Stat title="Monthly allocated rent" value={fmtUGX(room.summary.monthly_rent)} note={room.month}/><Stat title="Unpaid rent due" value={fmtUGX(room.summary.due_balance)} note="Stay agreement invoices"/><Stat title="Open repairs" value={room.summary.open_repairs} note={`${room.summary.visitors_on_site} visitors checked in / overdue`}/></div>
    <nav className="room-tabs" aria-label="Room sections">{tabs.map(tab=><button key={tab} type="button" className={`room-tab ${active===tab?'active':''}`} aria-pressed={active===tab} onClick={()=>setParams(tab==='Overview'?{}:{tab})}>{tab}{counts[tab]!==undefined&&<span>{counts[tab]}</span>}</button>)}</nav>
    <section aria-label={active}>
    {active==='Overview'&&<>
      <div className="room-overview-grid"><div className="card"><h2 className="section-title">Current occupants</h2>{room.occupants.length?room.occupants.map(o=><div className="room-occupant" key={o.id}><div className="room-occupant-heading"><Avatar src={o.photo_path} first={o.first_name} last={o.last_name} size={48}/><div><strong>{o.first_name} {o.last_name}</strong><p className="dim">{o.unpriced?'Rent agreement needed':tenantTypes[o.tenant_type]||'Tenant'}</p></div><Link className="btn btn-sm" to={`/residents?q=${encodeURIComponent(`${o.first_name} ${o.last_name}`)}`}>Resident details</Link></div><dl className="room-facts"><Fact name="Phone" value={o.phone}/><Fact name="Email" value={o.email}/><Fact name="National ID" value={o.national_id}/><Fact name="Stay starts" value={o.stay_start||o.move_in_date}/><Fact name="Stay ends" value={o.unpriced?o.move_out_date:o.stay_end}/></dl>{o.notes&&<p className="room-note">{o.notes}</p>}</div>):<Empty text="No occupants staying here today."/>}</div>
      <div className="card"><h2 className="section-title">Room notes & attention</h2><p className="room-note">{room.notes||'No room notes recorded.'}</p><div className="room-attention"><span>Repairs needing attention</span><strong>{room.summary.open_repairs}</strong></div><div className="room-attention"><span>Visitors checked in / overdue</span><strong>{room.summary.visitors_on_site}</strong></div><div className="room-attention"><span>Cash received · {room.month}</span><strong>{fmtUGX(room.summary.cash_this_month)}</strong></div>{room.occupants.some(o=>o.unpriced)&&<Link className="occupancy-notice" to={`/?room=${room.id}`}>Add rent terms for unpriced occupants →</Link>}<p className="form-help">Occupancy follows recorded stay dates. The room status above is its separately configured operational status.</p></div></div>
      <div className="card room-activity"><h2 className="section-title">Recent room activity</h2><Activity events={room.events.slice(0,12)}/></div>
    </>}
    {active==='Occupant history'&&<div className="card"><h2 className="section-title">Past, current & upcoming stays</h2>{room.stays.length?<Table headings={['Occupant','Category','Dates','Agreed rate','State']} rows={room.stays.map(s=>[<strong>{s.first_name} {s.last_name}</strong>,tenantTypes[s.tenant_type],<>{s.start_date}<br/>{s.end_date}</>,<>{fmtUGX(s.amount)}<div className="dim">{s.billing_basis==='monthly'?'Per calendar month':'Total for the stay'}</div></>,s.state])}/>:<p className="dim">No dated rent agreements recorded for this room.</p>}{room.legacy_assignments.length>0&&<><h3 className="section-title" style={{marginTop:24}}>Legacy occupant assignments</h3><p className="form-help">Known assignments before rent agreements were entered. Missing dates are shown explicitly; earlier room transfers cannot be reconstructed from these records.</p><Table headings={['Occupant','From','Until','Contact']} rows={room.legacy_assignments.map(r=>[`${r.first_name} ${r.last_name}`,r.history_start||'Not recorded',r.history_end||'End not recorded',r.phone||r.email||'—'])}/></>}</div>}
    {active==='Rent & receipts'&&<>
      <div className="card"><div className="page-head" style={{marginBottom:12}}><h2 className="section-title" style={{margin:0}}>Stay rent invoices</h2><Link className="btn btn-sm btn-primary" to={`/?room=${room.id}`}>Manage rent & record receipts →</Link></div>{invoices.length?<Table headings={['Tenant','Coverage','Due','Billed','Paid','Balance']} rows={invoices.map(i=>[i.resident_name,<>{i.period_start}<br/>{i.period_end}</>,i.due_date,fmtUGX(i.amount),fmtUGX(i.paid),fmtUGX(i.balance)])}/>:<Empty text="No stay invoices yet. Add a rent agreement to generate them."/>}</div>
      <div className="card room-activity"><h2 className="section-title">Rent receipts</h2>{room.receipts.length?<Table headings={['Tenant','Received','Amount','Method','Reference']} rows={room.receipts.map(r=>[r.resident_name,r.paid_on,fmtUGX(r.amount),r.method.replaceAll('_',' '),r.reference||'—'])}/>:<p className="dim">No stay receipts recorded.</p>}</div>
      <div className="card room-activity"><h2 className="section-title">Manual & legacy payments</h2><p className="form-help">Shown separately from stay rent. “Legacy association” means the room was inferred during migration and may not reflect an earlier room transfer.</p>{room.legacy_payments.length?<Table headings={['Resident','Type','Amount','Status','Due / paid','Room association']} rows={room.legacy_payments.map(p=>[`${p.resident_first||''} ${p.resident_last||''}`,p.type,fmtUGX(p.amount),<Badge value={p.status}/>,<>{p.due_date||'—'}<br/>{p.paid_at||'—'}</>,p.room_attribution==='legacy'?'Legacy association':'Recorded room'])}/>:<p className="dim">No manual payments associated with this room.</p>}</div>
    </>}
    {active==='Repairs'&&<div className="card"><div className="page-head" style={{marginBottom:12}}><h2 className="section-title" style={{margin:0}}>Repair & maintenance history</h2><button className="btn btn-primary" onClick={()=>setRepairing(true)}>+ Log repair</button></div>{room.repairs.length?room.repairs.map(r=><div className="room-repair" key={r.id}><div><strong>{r.description}</strong><p className="dim">{r.category||'General'} · {r.resident_first?`${r.resident_first} ${r.resident_last}`:'Management report'}</p><p className="room-record-meta">Reported {fmtDateTime(r.created_at)} · Updated {fmtDateTime(r.updated_at)}<br/>Assigned to: {r.assigned_to||'Unassigned'}</p></div><div className="repair-controls"><Badge value={r.priority}/><select className="select" aria-label={`Status for ${r.description}`} disabled={updating===r.id} value={r.status} onChange={e=>repairStatus(r,e.target.value)}>{['open','assigned','in_progress','resolved','escalated'].map(status=><option key={status} value={status}>{status.replaceAll('_',' ')}</option>)}</select></div></div>):<Empty text="No repairs recorded for this room."/>}</div>}
    {active==='Visits'&&<div className="card"><div className="page-head" style={{marginBottom:12}}><h2 className="section-title" style={{margin:0}}>Visitor history</h2><Link className="btn btn-sm" to={`/visitors?room=${room.id}`}>Open visitor register →</Link></div><p className="form-help">Recorded room associations stay with this room when the host moves. Older inferred records are marked as legacy.</p>{room.visits.length?<Table headings={['Guest / reference','Host','Status','Expected visit','Check-in / out','Association']} rows={room.visits.map(v=>[<><strong>{v.guest_name}</strong><div className="dim">{v.ref} · {v.purpose||'Visit'}</div><div className="dim">{v.guest_phone||''}</div></>,`${v.resident_first||'Unknown'} ${v.resident_last||''}`,<Badge value={v.status}/>,<>{fmtDateTime(v.expected_arrival)}<br/>{fmtDateTime(v.expected_departure)}</>,<>{fmtDateTime(v.check_in_time)}<br/>{fmtDateTime(v.check_out_time)}</>,v.room_attribution==='legacy'?'Legacy association':'Recorded room'])}/>:<Empty text="No visitor records associated with this room."/>}</div>}
    {active==='Inspections'&&<div className="card"><div className="page-head" style={{marginBottom:12}}><h2 className="section-title" style={{margin:0}}>Inspections, keys & deposits</h2><button className="btn btn-primary" onClick={()=>setInspecting(true)}>+ Record inspection</button></div>{room.inspections.length?room.inspections.map(i=><div className="room-inspection" key={i.id}><div className="occupancy-room-top"><strong>{i.inspection_date||'Date not recorded'}</strong><Badge value={i.deposit_status}/></div><p className="room-note">{i.condition_notes||'No condition notes recorded.'}</p><div className="room-record-meta">Resident: {i.resident_first?`${i.resident_first} ${i.resident_last}`:'Room inspection'} · Keys {i.returned_keys?'returned':'not returned'} · Proposed deductions: {fmtUGX(i.deductions_proposed)}</div></div>):<Empty text="No inspections recorded for this room."/>}</div>}
    </section>
    {editing&&<RoomForm room={room} onClose={()=>setEditing(false)} onSaved={()=>{setEditing(false);load();}}/>}
    {repairing&&<RepairForm room={room} onClose={()=>setRepairing(false)} onSaved={()=>{setRepairing(false);load();}}/>}
    {inspecting&&<InspectionForm room={room} onClose={()=>setInspecting(false)} onSaved={()=>{setInspecting(false);load();}}/>}
  </div>;
}
function Stat({title,value,note}){return <div className="stat-card"><div className="stat-value" style={{fontSize:24}}>{value}</div><div className="stat-label">{title}</div><p className="metric-note">{note}</p></div>;}
function Fact({name,value}){return <div><dt>{name}</dt><dd>{value||'Not recorded'}</dd></div>;}
function Table({headings,rows}){return <div className="table-wrap"><table className="table"><thead><tr>{headings.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>;}
function Activity({events}){return events.length?<ol className="room-timeline">{events.map(e=><li key={e.id}><span className="room-timeline-dot"/><div><span className="room-record-meta">{e.type} · {fmtDateTime(e.date)}</span><strong>{e.title}</strong><p>{e.detail}</p></div></li>)}</ol>:<p className="dim">No room activity recorded yet.</p>;}
function Field({label,id,children}){return <div className="field"><label htmlFor={id}>{label}</label>{children}</div>;}
function RepairForm({room,onClose,onSaved}){
  const [form,setForm]=useState({room_id:room.id,description:'',category:'General',priority:'normal',assigned_to:'',resident_id:''});const [busy,setBusy]=useState(false);const toast=useToast();const set=(k,v)=>setForm(f=>({...f,[k]:v}));
  async function submit(e){e.preventDefault();setBusy(true);try{await api.post('/maintenance',form);toast('Repair logged for this room.');onSaved();}catch(e){toast(e.message,'error');}finally{setBusy(false);}}
  return <Modal title={`Log repair · ${room.name}`} onClose={onClose}><form onSubmit={submit}><Field label="Description" id="repair-description"><textarea id="repair-description" className="textarea" required value={form.description} onChange={e=>set('description',e.target.value)}/></Field><div className="form-row"><Field label="Trade" id="repair-trade"><select id="repair-trade" className="select" value={form.category} onChange={e=>set('category',e.target.value)}>{TRADES.map(t=><option key={t.id} value={t.label}>{t.label}</option>)}</select></Field><Field label="Priority" id="repair-priority"><select id="repair-priority" className="select" value={form.priority} onChange={e=>set('priority',e.target.value)}>{['low','normal','high','urgent'].map(p=><option key={p}>{p}</option>)}</select></Field></div><Field label="Reported by" id="repair-resident"><select id="repair-resident" className="select" value={form.resident_id} onChange={e=>set('resident_id',e.target.value)}><option value="">Management</option>{room.occupants.map(o=><option key={o.id} value={o.id}>{o.first_name} {o.last_name}</option>)}</select></Field><Field label="Assigned to" id="repair-assignee"><input id="repair-assignee" className="input" value={form.assigned_to} onChange={e=>set('assigned_to',e.target.value)} placeholder="Person or maintenance team"/></Field><button className="btn btn-primary" disabled={busy}>{busy?'Saving…':'Log repair'}</button></form></Modal>;
}
function InspectionForm({room,onClose,onSaved}){
  const [form,setForm]=useState({room_id:room.id,resident_id:'',inspection_date:today(),condition_notes:'',returned_keys:false,deductions_proposed:0,deposit_status:'pending'});const [busy,setBusy]=useState(false);const toast=useToast();const set=(k,v)=>setForm(f=>({...f,[k]:v}));
  async function submit(e){e.preventDefault();setBusy(true);try{await api.post('/inspections',form);toast('Inspection recorded for this room.');onSaved();}catch(e){toast(e.message,'error');}finally{setBusy(false);}}
  return <Modal title={`Inspection · ${room.name}`} onClose={onClose}><form onSubmit={submit}><div className="form-row"><Field label="Date" id="inspection-date"><input id="inspection-date" className="input" required type="date" value={form.inspection_date} onChange={e=>set('inspection_date',e.target.value)}/></Field><Field label="Resident" id="inspection-resident"><select id="inspection-resident" className="select" value={form.resident_id} onChange={e=>set('resident_id',e.target.value)}><option value="">Room inspection</option>{room.occupants.map(o=><option key={o.id} value={o.id}>{o.first_name} {o.last_name}</option>)}</select></Field></div><Field label="Condition notes" id="inspection-notes"><textarea id="inspection-notes" className="textarea" required value={form.condition_notes} onChange={e=>set('condition_notes',e.target.value)}/></Field><div className="form-row"><Field label="Proposed deductions (UGX)" id="inspection-deductions"><input id="inspection-deductions" className="input" type="number" min="0" step="1" value={form.deductions_proposed} onChange={e=>set('deductions_proposed',Number(e.target.value))}/></Field><Field label="Deposit status" id="inspection-deposit"><select id="inspection-deposit" className="select" value={form.deposit_status} onChange={e=>set('deposit_status',e.target.value)}>{['pending','proposed','disputed','approved','refunded','settled'].map(s=><option key={s}>{s}</option>)}</select></Field></div><label className="inspection-key-check"><input type="checkbox" checked={form.returned_keys} onChange={e=>set('returned_keys',e.target.checked)}/> Keys returned</label><button className="btn btn-primary" disabled={busy}>{busy?'Saving…':'Record inspection'}</button></form></Modal>;
}
