import React,{useEffect,useState} from 'react';
import {api} from '../api.js';
import {useToast,fmtDateTime} from '../components/ui.jsx';
import Brand from '../components/Brand.jsx';
export default function Settings({user,onUserChanged}){
 const toast=useToast();
 const [form,setForm]=useState(null),[saved,setSaved]=useState(null),[integrations,setIntegrations]=useState(null),[profile,setProfile]=useState({full_name:user.full_name,phone:user.phone||''}),[saving,setSaving]=useState(false),[profileBusy,setProfileBusy]=useState(false),[checking,setChecking]=useState(false),[check,setCheck]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false;Promise.all([api.get('/settings'),api.get('/settings/integrations')]).then(([s,i])=>{if(cancelled)return;const {updated_at,...fields}=s;setForm(fields);setSaved(s);setIntegrations(i);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[]);
 const set=(key,value)=>setForm(f=>({...f,[key]:value}));
 const dirty=form&&saved&&Object.keys(form).some(k=>form[k]!==saved[k]);
 async function save(e){e.preventDefault();setSaving(true);try{const result=await api.put('/settings',form);setSaved(result);const {updated_at,...fields}=result;setForm(fields);toast('Hostel settings saved');}catch(e){toast(e.message,'error');}finally{setSaving(false);}}
 async function saveProfile(e){e.preventDefault();setProfileBusy(true);try{const next=await api.put('/settings/profile',profile);onUserChanged(next);setProfile({full_name:next.full_name,phone:next.phone||''});toast('Profile updated');}catch(e){toast(e.message,'error');}finally{setProfileBusy(false);}}
 async function checkSms(){setChecking(true);setCheck(null);try{setCheck(await api.post('/settings/sms-check',{}));}catch(e){setCheck({verified:false,message:e.message});}finally{setChecking(false);}}
 return <div className="stagger"><div className="page-head"><div><div className="eyebrow">Administration · Hostel preferences</div><h1 className="page-title">Settings</h1><p className="page-sub">Hostel identity, practical defaults and your connected services.</p></div></div>
 {error&&<p className="occupancy-notice" role="alert">{error}</p>}
 {!form&&!error&&<p role="status">Loading settings…</p>}
 {form&&<div className="settings-grid"><form className="card" onSubmit={save}><div className="settings-brand"><Brand/><div><h2 className="section-title">Hostel details</h2><p className="form-help">Used on finance reports and exports. The supplied New Nana logo remains the brand mark.</p></div></div>
  <SettingsField label="Hostel name" id="hostel-name"><input id="hostel-name" className="input" required maxLength="80" value={form.hostel_name} disabled={saving} onChange={e=>set('hostel_name',e.target.value)}/></SettingsField>
  <SettingsField label="Address" id="hostel-address"><textarea id="hostel-address" className="textarea" rows="2" maxLength="250" value={form.address} disabled={saving} onChange={e=>set('address',e.target.value)}/></SettingsField>
  <div className="form-row"><SettingsField label="Contact phone" id="hostel-phone"><input id="hostel-phone" type="tel" className="input" maxLength="40" value={form.phone} disabled={saving} onChange={e=>set('phone',e.target.value)}/></SettingsField><SettingsField label="Contact email" id="hostel-email"><input id="hostel-email" type="email" className="input" maxLength="120" value={form.email} disabled={saving} onChange={e=>set('email',e.target.value)}/></SettingsField></div>
  <SettingsField label="Report footer" id="report-footer"><textarea id="report-footer" className="textarea" rows="2" maxLength="250" value={form.report_footer} disabled={saving} onChange={e=>set('report_footer',e.target.value)}/></SettingsField>
  <h2 className="section-title settings-divider">New stay & receipt defaults</h2><p className="form-help">Prefills new Dashboard forms. Existing agreements, invoices and receipts retain their original values.</p>
  <div className="form-row"><SettingsField label="Default tenant category" id="default-category"><select id="default-category" className="select" value={form.default_tenant_type} disabled={saving} onChange={e=>set('default_tenant_type',e.target.value)}><option value="bachelor">University student</option><option value="ldc">LDC tenant</option><option value="other">Other tenant</option></select></SettingsField><SettingsField label="Default rent basis" id="default-basis"><select id="default-basis" className="select" value={form.default_billing_basis} disabled={saving} onChange={e=>set('default_billing_basis',e.target.value)}><option value="fixed">Fixed term / semester total</option><option value="monthly">Monthly rent</option></select></SettingsField></div>
  <SettingsField label="Default receipt method" id="default-method"><select id="default-method" className="select" value={form.default_payment_method} disabled={saving} onChange={e=>set('default_payment_method',e.target.value)}>{['cash','bank','mtn_momo','airtel_money','other'].map(m=><option key={m} value={m}>{m.replaceAll('_',' ')}</option>)}</select></SettingsField>
  <div className="settings-policy"><strong>Agreed billing rules</strong><p>Semester: 3 months · Monthly rent: full calendar months · Currency: UGX · Time zone: Africa/Kampala</p><span>Rates are entered per resident. These rules preserve the current ledger.</span></div>
  <div className="agreement-actions"><button className="btn btn-primary" disabled={saving||!dirty}>{saving?'Saving…':'Save hostel settings'}</button><button type="button" className="btn" disabled={saving||!dirty} onClick={()=>{const {updated_at,...fields}=saved;setForm(fields);}}>Discard changes</button></div><p className="form-help" role="status">{dirty?'Unsaved changes':saved.updated_at?`Saved ${fmtDateTime(saved.updated_at)}`:'Using initial hostel defaults'}</p>
 </form><div className="settings-side"><form className="card" onSubmit={saveProfile}><div className="eyebrow">Your account</div><h2 className="section-title">Profile</h2><p className="form-help">Signed in as @{user.username} · {user.role}</p><SettingsField label="Full name" id="profile-name"><input id="profile-name" className="input" required maxLength="100" value={profile.full_name} disabled={profileBusy} onChange={e=>setProfile(p=>({...p,full_name:e.target.value}))}/></SettingsField><SettingsField label="Phone" id="profile-phone"><input id="profile-phone" type="tel" className="input" maxLength="40" value={profile.phone} disabled={profileBusy} onChange={e=>setProfile(p=>({...p,phone:e.target.value}))}/></SettingsField><button className="btn" disabled={profileBusy||profile.full_name===user.full_name&&profile.phone===(user.phone||'')}>{profileBusy?'Saving…':'Save profile'}</button></form>
 <section className="card"><div className="eyebrow">Connected services</div><h2 className="section-title">Integrations</h2><div className="settings-integration"><strong>Africa’s Talking SMS</strong><span className={`settings-status ${integrations?.sms.configured?'ready':''}`}>{integrations?.sms.configured?'Credentials configured':'Not configured'}</span><p className="form-help">{integrations?.sms.mode==='live'?'Live · sends are billable':'Sandbox · simulator only'} · Sender: {integrations?.sms.sender}</p><p className="form-help">Configured credentials do not guarantee authentication or delivery. This check reads your provider account; it sends no SMS.</p><button className="btn btn-sm" type="button" disabled={checking||!integrations?.sms.configured} onClick={checkSms}>{checking?'Checking…':'Check SMS connection'}</button>{check&&<p className={check.verified?'form-help':'announcement-ai-error'} role="status">{check.message}</p>}</div><div className="settings-integration"><strong>OpenAI announcement rewrite</strong><span className={`settings-status ${integrations?.openai.configured?'ready':''}`}>{integrations?.openai.configured?'Credentials configured':'Not configured'}</span><p className="form-help">Model: {integrations?.openai.model} · Rewrites stay as suggestions until you accept them.</p></div><p className="form-help">API keys stay in the private server environment. They are never displayed here. Update the server configuration and restart the backend to change providers or credentials.</p></section>
 </div></div>}
 </div>;
}
function SettingsField({label,id,children}){return <div className="field"><label htmlFor={id}>{label}</label>{children}</div>;}
